# Generated by Django 4.0.4 on 2022-04-12 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_squashed_0006_alter_canvas_id_alter_pixel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=5)),
                ('lastPost', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='canvas',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='canvas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.canvas'),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='position',
            field=models.PositiveIntegerField(),
        ),
    ]
