# Generated by Django 4.0.4 on 2022-04-15 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_tempuser_alter_canvas_title_alter_pixel_canvas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixel',
            name='canvas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pixels', to='testing.canvas'),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='color',
            field=models.CharField(max_length=1),
        ),
    ]
