# Generated by Django 4.0.3 on 2022-04-11 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_canvas_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField()),
                ('y', models.PositiveSmallIntegerField()),
                ('color', models.PositiveSmallIntegerField()),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.canvas')),
            ],
        ),
    ]
