# Generated by Django 4.0.3 on 2022-04-11 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_pixel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pixel',
            name='x',
        ),
        migrations.RemoveField(
            model_name='pixel',
            name='y',
        ),
        migrations.AddField(
            model_name='pixel',
            name='position',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pixel',
            name='canvas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pixels', to='testing.canvas'),
        ),
    ]
