# Generated by Django 2.2.28 on 2022-04-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_remove_pixel_x_remove_pixel_y_pixel_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
